#!/usr/bin/env python
# -*- coding: UTF-8 -*-
'''
Author      : Dong Junshuang
Description : 越南 钻石存量前100
'''
import settings
from utils import hqls_to_dfs, update_mysql, ds_add
from pandas import Series,DataFrame
from utils import get_config
import pandas as pd


if __name__ == '__main__':
    settings.set_env('superhero_vt')
    act_sql = '''
    SELECT uid,
           zuanshi,
           LEVEL,
           vip_level
    FROM
      (SELECT ds,
              uid,
              zuanshi,
              LEVEL,
              vip_level,
              row_number() over(partition BY uid
                                ORDER BY ds DESC) AS rn
       FROM raw_info
       WHERE ds >='20160917'
         AND ds<='20160923' )a
    WHERE rn =1
    ORDER BY zuanshi DESC LIMIT 100
    '''
    pay_sql = '''
    SELECT uid,
           max(order_time) order_time
    FROM mid_paylog_all
    WHERE ds = '20160923'
    GROUP BY uid
    '''
    act_df,pay_df = hqls_to_dfs([act_sql,pay_sql])

    data = act_df.merge(pay_df,on = 'uid',how='left')

    data.to_excel('/Users/kaiqigu/Downloads/Excel/coin_save.xlsx')

